void alocarMatriz(int x[1], int y[1]);
int testarReserva(int z[1], int w[1]);
int testarCheckin(int z[1], int w[1]);
int testarCheckout(int z[1], int w[1]);
int testarCancelaReserva(int z[1], int w[1]);
void addInfoHospede(int z[1], int w[1]);
int conferirLotacao();
void reservar();
void checkin();
void checkout();
void cancelarReserva();
void quartosReservado();
void taxaOcupacao();
void infoHospedes();
void imprimirMapa();
